VALUE_SET_FOLDER_ID = '1YA1SCCdzPCvz2FI9lMwsM3xq9BX9pHpr'
WIP_FOLDER_ID = '1xtyVepStirebLfeEArItCI9lUR89kmcT'
READY_FOLDER_ID = '1PNjBH3L4u0myl4PNZt6lt2pahkOFYHqC'
DONE_FOLDER_ID = '1T3QAyVKR-iYqJplYfW2SrPA2XWbpBqsA'
FAIL_FOLDER_ID = '1Gs02lhN52IUDAsIwSudBJKjv4nzt9_9k'
STAGING_FOLDER_ID = '1UGR1jRhD3wPSk-FTfHm43nCcgi3uWmNn'

SOURCE_SHEET_ID = '1owc72ZKznnVNZ6M78aJVcj5Lm4DbeOMmUFy13oImQ78' #current test codelist for processing
NAMESPACE_SHEET_ID = '1yiuq8NqECKTOtOMLLlKzOC3oL1nvS9epd6_wEWVYBcw'
PEOPLE_ORG_SHEET_ID = '1UPq83LQcQbe8HfabFlyLB2Tso196dsII9uBvqa72HS4'
QUALIFIER_AND_TIMING_SHEET_ID = '1PaJKPmmaj6GEDzy9yb6mTuSKa3NBXKz-oprDkGDqRVs'
STATEMENT_SHEET_ID = '1zKweaaYACMpeaWWijCvACYEV3IDFRkzjyiU_G7FPs4M'
STATEMENT_TAB_NAME = 'Statements'
CRITERION_SHEET_ID = '1onewv2d1APxVafAWaiFBcilelVK9shFiHstQNvf8gjs'
CRITERION_TAB_NAME = 'Criteria'
# CRITERION_TAB_NAME = 'Criteria (az_valor_desc_va)'
STUDY_SHEET_ID = '1ixpf2WQHQRX1dVy6KIePo-3AGi3BwMt1OKC9yYcbZJM'
STUDY_TAB_NAME = 'Study List'

STUDY_HANDLE_LIST = [
    'az_valor_desc_va',
    # 'az_valor_effectiveness_dod'
]
